<?php

// ReportController handles generation of PDF reports for the library system
require_once __DIR__ . '/../../../main.php';
require_once __DIR__ . '/../../../vendor/autoload.php';
require_once Config::getModelPath('staff', 'librarysetupmodel.php');

use Dompdf\Dompdf;

class ReportController extends Controller
{
    private $librarySetupModel;

    public function __construct()
    {
        // Load the LibrarySetup model for retrieving library info like logo
        require_once Config::getModelPath('staff', 'librarysetupmodel.php');
        $this->librarySetupModel = new LibrarySetupModel();
    }

    // Generate and serve PDF report
    public function generateReport()
    {
        // Log the report generation request
        Logger::info("Report generation requested", [
            'title' => $_POST['title'] ?? null,
            'filename' => $_POST['filename'] ?? null,
        ]);

        // Get report details from POST, set defaults if missing
        $reportTitle = $_POST['title'] ?? 'Library Report';
        $fileName = $_POST['filename'] ?? 'report.pdf';
        $tableHtml = $_POST['table_html'] ?? '<p>No data available</p>';

        // Get library logo in base64 format to embed in PDF
        $logoPath = $this->getLogoBase64();

        $currentDate = date('Y-m-d');

        // Build full HTML content for the PDF
        $html = "
        <html>
        <head>
            <style>
                h2 { text-align: center; margin-bottom: 0; }
                .report-date { text-align: center; margin-top: 5px; margin-bottom: 20px; font-size: 14px; }
                .footer { text-align: center; margin-top: 30px; font-style: italic; font-size: 12px; }

                table { width: 100%; border-collapse: collapse; }
                th, td { border: 1px solid #000; padding: 3px; text-align: left; }
                th { background-color: #f2f2f2; }
            </style>
        </head>
        <body>
            <table width='100%' style='background-color:rgb(104, 104, 104); color: white;'>
                <tr>
                    <td style='width: 20%; text-align: left; border: none;'>
                        <img src='$logoPath' height='60' alt='Logo'>
                    </td>
                    <td style='width: 60%; text-align: center; border: none;'>
                        <h2 style='margin: 0; color: white;'>$reportTitle</h2>
                    </td>
                    <td style='width: 20%; text-align: right; font-size: 15px; border: none;'>
                        <p style='text-align: center;'>Date<br> $currentDate</p>
                    </td>
                </tr>
            </table>
        <div style='margin-top: 10px'> $tableHtml</div>
            <div class='footer'>Generated by Library Management System</div>
        </body>
        </html>
    ";

        try {
            // Initialize Dompdf and render PDF
            $dompdf = new Dompdf();
            $dompdf->loadHtml($html);
            $dompdf->setPaper('A4', 'landscape');
            $dompdf->render();
            // Stream PDF to browser without forcing download
            $dompdf->stream($fileName, ["Attachment" => false]);
            exit;
        } catch (\Exception $e) {
            // Log error if PDF generation fails
            Logger::error("Failed to generate report PDF", [
                'message' => $e->getMessage(),
                'trace' => $e->getTraceAsString()
            ]);
            http_response_code(500);
            echo "Error generating report PDF.";
            exit;
        }
    }

    // Retrieve library logo as base64 to embed in PDF
    private function getLogoBase64()
    {
        $libraryData = LibrarySetupModel::getLibraryInfo();
        $logo = $libraryData['logo'] ?? '';

        $path = Config::getLogoPath() . $logo;

        if (file_exists($path)) {
            // Convert logo file to base64 format
            $imageData = file_get_contents($path);
            $mimeType = mime_content_type($path); // e.g., image/png or image/jpeg
            $base64 = 'data:' . $mimeType . ';base64,' . base64_encode($imageData);
            return $base64;
        }

        // Fallback if logo file is missing
        Logger::warning("Library logo not found, using fallback", ['path' => $path]);
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4//8/AwAI/AL+KDVaWQAAAABJRU5ErkJggg==';
    }
}
